version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    command: npm run dev
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://mongo:27017/livestream
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=devsecret
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    working_dir: /app
  frontend:
    build: ./frontend
    command: npm run dev
    environment:
      - NEXT_PUBLIC_WS_URL=http://localhost:4000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    depends_on:
      - backend
  ai:
    build: ./ai-recommendation
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./ai-recommendation:/app
    working_dir: /app
volumes:
  mongo_data:
