name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
        ports: ['27017:27017']
      redis:
        image: redis:7-alpine
        ports: ['6379:6379']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install shared
        run: |
          cd shared && npm install
      - name: Install backend
        run: |
          cd backend && npm install
      - name: Build backend
        run: |
          cd backend && npm run build
      - name: Run tests
        run: |
          cd backend && npm test
      - name: Frontend install & type check
        run: |
          cd frontend && npm install && npx tsc --noEmit
